### ISSUE TITLE
Button block link color affected by container background color

### ISSUE THREAD

**Issue by tragessere** [Purdue/purdue-wp-theme#103]
All links below containers with a background color are having their color updated, and I'm thinking this should just affect direct children instead. When using a block button the link has a black background around it, but the text color is still being overridden which puts the text just below AA contrast compliance.

Here are two button blocks with a link (the anchor tag has class `wp-block-button__link`). One is inside a Bulma container with the background set to light gray

![image](https://user-images.githubusercontent.com/6559092/189153507-3304c383-29d7-40e8-a02a-d959aca16978.png)

The link colors here: https://github.com/Purdue/purdue-wp-theme/blob/master/src/style/front-end/components/links.scss

For a live example, the button is being used on our site at the bottom of the page here: www.purdue.edu/innovativelearning/developing-courses/launch-process/

**Comment by Yanhuazong** [comment]
Thank you for reporting this issue. Sometimes the paragraph may not be the direct child of the container so I applied a fix to exclude the button class for now.

**Comment by tragessere** [comment]
I know the color changed since I reported it, but it's looking great now. Thanks for the fix!

**Comment by Yanhuazong** [comment]
Thank you! As an alternative you can also use the Purdue button block in the purdue blocks plugin, which doesn’t have the alignment option but has better color definition.Thanks!Best regards,Yanhua On Dec 14, 2022, at 8:43 AM, tragessere ***@***.***> wrote:﻿
I know the color changed since I reported it, but it's looking great now. Thanks for the fix!
